export default {
    keyInputDownArrow: 'keyInputDownArrow',
    keyInputEscape: 'keyInputEscape',
    keyInputLeftArrow: 'keyInputLeftArrow',
    keyInputRightArrow: 'keyInputRightArrow',
    keyInputUpArrow: 'keyInputUpArrow',
    keyInputEnter: 'keyInputEnter',
    keyModifierCapsLock: 'keyModifierCapsLock',
    keyModifierCommand: 'keyModifierCommand',
    keyModifierControl: 'keyModifierControl',
    keyModifierControlCommand: 'keyModifierControlCommand',
    keyModifierControlOption: 'keyModifierControlOption',
    keyModifierControlOptionCommand: 'keyModifierControlOptionCommand',
    keyModifierNumericPad: 'keyModifierNumericPad',
    keyModifierOption: 'keyModifierOption',
    keyModifierOptionCommand: 'keyModifierOptionCommand',
    keyModifierShift: 'keyModifierShift',
    keyModifierShiftCommand: 'keyModifierShiftCommand',
    keyModifierShiftControl: 'keyModifierShiftControl',
    keyModifierAlternate: 'keyModifierAlternate'
};
